source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'YQBase_Example' do
  pod 'YQBase', :path => '../'

  target 'YQBase_Tests' do
    inherit! :search_paths

    
  end
end
